services:
  node:
    build:
      context: .
      dockerfile: ./docker/node.Dockerfile
    container_name: pm_node
    working_dir: /usr/local/app
    command: sh -c "npx sequelize-cli db:migrate && npm run migrate && node ./configurations/generateData/dataInit.js && nodemon index.js"
    volumes:
      - ./server:/usr/local/app
      - server_node_modules_vol:/usr/local/app/node_modules
      - ./server/db:/usr/local/app/db
    ports:
      - "3000:3000"

  react:
    image: node:18
    container_name: pm_react
    working_dir: /usr/local/app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./client:/usr/local/app
      - client_node_modules_vol:/usr/local/app/node_modules
    ports:
      - "5173:5173"

  mailcatcher:
    image: schickling/mailcatcher
    container_name: pm_mailcatcher
    ports:
      - "1080:1080" # web
      - "1025:1025" # smtp

volumes:
  server_node_modules_vol:
  client_node_modules_vol:
